# To get started with Dependabot version updates, you'll need to specify which
# package ecosystems to update and where the package manifests are located.
# Please see the documentation for all configuration options:
# https://docs.github.com/github/administering-a-repository/configuration-options-for-dependency-updates

version: 2
updates:
  - package-ecosystem: "pip" # Para proyectos Python
    directory: "/" # El directorio donde se encuentra tu archivo de dependencias (requirements.txt o pipfile)
    schedule:
      interval: "daily" # Dependabot comprobará las actualizaciones diariamente
    open-pull-requests-limit: 10 # El número máximo de pull requests abiertas de Dependabot
    reviewers: # Dependabot asignará a estos revisores a las pull requests
      - "username1"
      - "username2"
    assignees: # Dependabot asignará a estos usuarios a las pull requests
      - "username1"
      - "username2"
